
FROM ubuntu:21.04
ENV JAVA_HOME=/u01/lib/jdk-11
ENV PATH=${PATH}:${JAVA_HOME}/bin

RUN mkdir -p /u01/lib/

WORKDIR /u01/lib/

RUN echo "getting ready for jdk download"
RUN apt update -y
RUN apt install -y curl

RUN curl https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz --output openjdk-11+28_linux-x64_bin.tar.gz
RUN gunzip openjdk-11+28_linux-x64_bin.tar.gz
RUN tar -xvf openjdk-11+28_linux-x64_bin.tar
RUN rm -rf openjdk-11+28_linux-x64_bin.tar
CMD ["/bin/bash","-c","java -version"]

COPY target/covido-0.0.1-SNAPSHOT.war   .
RUN chmod u+x covido-0.0.1-SNAPSHOT.war

COPY startup.sh .
RUN chmod u+x startup.sh
ENTRYPOINT ["./startup.sh"]

#HEALTHCHECK --interval=35s --timeout=4s CMD curl -f https://localhost/ || exit 1
